### ISSUE TITLE
Validation of appointments

### ISSUE THREAD

**Issue by autark** [FirelyTeam/fhir-net-api#1125]
[Reporting this issue based on [this conversation](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Validating.20appointments/near/176454262) on chat.fhir.org]

While trying to validate an Appointment resource (attached) using the base profile provided by v1.3.0 of the Hl7.Fhir.R4 packages, I keep getting the following errors and warnings:
```
Value=1006 Description=Resource validation error. Overall result: FAILURE (1 errors and 1 warnings)

[WARNING] Evaluation of FhirPath for constraint 'app-4' failed: Invocation of 'binary.implies' failed: Invocation of 'exists' failed: Invocation of 'builtin.children' failed: Resource type name may only appear at the root of a document (at Bundle.entry[5].resource[0])
[ERROR] Instance failed constraint app-4 "Cancelation reason is only used for appointments that have been cancelled, or no-show"(further diagnostics: Appointment.cancelationReason.exists() implies (Appointment.status='no-show' or Appointment.status='cancelled')) (at Bundle.entry[5].resource[0])
```
The warning and error triggers even though the Appointment in question does not contain a cancelationReason, and the status is not cancelled or no-show.

[bundleWithAppointment.txt](https://github.com/FirelyTeam/fhir-net-api/files/3657767/bundleWithAppointment.txt)

**Comment by marcovisserFurore** [comment]
This has been solved in version 1.4.0.

You can check this by validate the following resource to the Vonk server (which is using version 1.4.0 of the Fhir-net-api already):

`POST https://vonk.fire.ly/r4/Appointment/$validate`

```
 {
	"resourceType": "Appointment",
	"id": "f1b652f7-61c5-4036-a897-9935b245b30c",
	"status": "booked",
	"start": "2019-08-03T08:00:00+02:00",
	"end": "2019-08-03T08:30:00+02:00",
	"participant": [
	  {
	    "actor": {
	      "reference": "Practitioner/d33a6cd1-7127-4eaf-b6fc-45c28a5277b0"
	    },
	    "status": "accepted"
	  }
	]
 }
```

**Comment by mustiks** [comment]
It's not fixed when Appointment is in Bundle

https://vonk.fire.ly/r4/Bundle/$validate
Request
`{
  "resourceType": "Bundle",
  "id": "18c8c73a-9d96-498f-95c3-3e8c59636177",
  "type": "collection",
  "entry": [
    {
      "fullUrl": "Practitioner/d33a6cd1-7127-4eaf-b6fc-45c28a5277b0",
      "resource": {
        "resourceType": "Practitioner",
        "id": "d33a6cd1-7127-4eaf-b6fc-45c28a5277b0",
        "name": [
          {
            "family": "Ohlsson",
            "given": [
              "Olle"
            ]
          }
        ]
      }
    },
    {
      "fullUrl": "Appointment/f1b652f7-61c5-4036-a897-9935b245b30c",
      "resource": {
        "resourceType": "Appointment",
        "id": "f1b652f7-61c5-4036-a897-9935b245b30c",
        "status": "booked",
        "start": "2019-08-03T08:00:00+02:00",
        "end": "2019-08-03T08:30:00+02:00",
        "participant": [
          {
            "actor": {
              "reference": "Practitioner/d33a6cd1-7127-4eaf-b6fc-45c28a5277b0"
            },
            "status": "accepted"
          }
        ]
      }
    }
  ]
}`

Responce
`{
  "resourceType": "OperationOutcome",
  "id": "77b5544c-ab01-459f-b78d-2298db4feab7",
  "meta": {
    "versionId": "0d539904-6deb-4f18-bb14-569a8c8255ef",
    "lastUpdated": "2020-01-27T08:54:48.977+00:00"
  },
  "issue": [
    {
      "severity": "warning",
      "code": "business-rule",
      "details": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
            "code": "2009"
          }
        ],
        "text": "Evaluation of FhirPath for constraint 'app-4' failed: Invocation of 'binary.implies' failed: Invocation of 'exists' failed: Invocation of 'builtin.children' failed: Resource type name may only appear at the root of a document"
      },
      "location": [
        "Bundle.entry[1].resource[0]"
      ]
    },
    {
      "severity": "error",
      "code": "invariant",
      "details": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
            "code": "1012"
          }
        ],
        "text": "Instance failed constraint app-4 \"Cancelation reason is only used for appointments that have been cancelled, or no-show\""
      },
      "diagnostics": "Appointment.cancelationReason.exists() implies (Appointment.status='no-show' or Appointment.status='cancelled')",
      "location": [
        "Bundle.entry[1].resource[0]"
      ]
    }
  ]
}`

**Comment by mustiks** [comment]
I think the problem is that constraint app-4 has absolute path, not relative
