### ISSUE TITLE
Snapshot generation fails for all Observation STU3 - making validation unavailable

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#1305]
Snapshot generation, and therefore validation, fails for all STU3 Observations based on the following error:

Element Quantity has an invalid non-empty sliceName 'SimpleQuantity'. Root element definitions cannot introduce slice names. Rule: http://hl7.org/fhir/StructureDefinition/SimpleQuantity

The profiles don't even mention a SimpleQuantity. Therefore, I expect that this error originates from the core spec. Below are examples where this goes wrong. 

**Depedency on hl7.fhir.r3.core	3.0.2**
- https://simplifier.net/nictizstu3-zib2017/observation-example-duplicate-18/$validate
- https://simplifier.net/nictizstu3-zib2017/observation-example-duplicate-4/$validate
- https://simplifier.net/nictizstu3-zib2017/observation-example-duplicate-21/$validate
- https://simplifier.net/nictizstu3-zib2017/observation-example/$validate

**Depedency op simplifier.core.stu3**
- https://simplifier.net/basisprofilde/observation-example-duplicate-4/$validate

**Validation against the base specification:**
- https://simplifier.net/validate?fhirVersion=STU3&snippetFileId=844

This may be related to:  
https://github.com/FirelyTeam/fhir-net-api/issues/618

**Comment by ArdonToonstra** [comment]
Great news. Solved with the latest release of Simplifier containing .NET API 1.6

**Comment by mmsmits** [comment]
Turns out this still occurs, we will suppress this warning, in a future hotfix

**Comment by ewoutkramer** [comment]
So, we now know why this happens: Simplifier throws away all snapshots, then the snapshot for SimpleQuantity will be re-generated, which then encounters this (incorrect) slicing in the root.  This has been fixed in later FHIR releases, but we will have to add a workaround, which I think @mmsmits is working on.

**Comment by ewoutkramer** [comment]
This will be fixed in 1.9

**Comment by marcovisserFurore** [comment]
This bug is related to #618 which has been fixed by suppressing the error message. The original error lies in the StructureDefinition of SimpleQuantity which has an incorrect slicing in the root. 

I will close this issue, while it has been solved in issue #618
