### ISSUE TITLE
Validator incorrectly triggers eld-13

### ISSUE THREAD

**Issue by mharthoorn** [FirelyTeam/fhir-net-api#874]
Validator triggers on an element definition type.code that contains only extensions

https://simplifier.net/snippet/mharthoorn/12/362/$validate

**Comment by wmrutten** [comment]
I recently updated the R4 SnapshotGenerator to handle extensions on primitive value element definitions, as the R4 validator requires this information. This improvement should also be backported to the STU3 branch (TODO).

**Comment by wmrutten** [comment]
What is the status of this issue? Has this been fixed in the latest API release for STU3?
Maybe you can review the validation on Simplifier.

**Comment by mbaltus** [comment]
This is not solved in version 1.3.0 of the library. I have tested this today. Steps to reproduce can be found in the duplicate issue.

**Comment by ArdonToonstra** [comment]
@marcovisserFurore , @mbaltus  and @wmrutten ,

I just reproduced the situation, as described in #1140,  with version 1.6.0-alpha. So it's not solved yet.

**Comment by ewoutkramer** [comment]
As @mharthoorn link does not work anymore, and @wmrutten's "I recently fixed" is too vague to reconstruct what was fixed here, I will close this issue and focus on #1140 - @mbaltus reports she was able to reproduce Martijn's issue, so I must trust that fixing #1140 will fix this issue too.
